---
- name: Add wireguard package archive
  apt_repository:
    repo: ppa:wireguard/wireguard

- name: Install wireguard package
  apt:
    name: wireguard
    state: present

- name: Ensure wireguard confiuration directory is present
  file:
    path: /etc/wireguard/
    state: directory
    mode: '0755'

- name: Check if a private key file already exists
  stat:
    path: "/etc/wireguard/privatekey"
  register: private_key_stat_result

- name: Generate a new private key if it does not exist yet
  shell: wg genkey > privatekey
  args:
    chdir: /etc/wireguard/
  when: private_key_stat_result.stat.exists == False

- name: Check if a public key file already exists
  stat:
    path: "/etc/wireguard/publickey"
  register: public_key_stat_result

- name: Generate the public key from the private key if it does not exist yet
  shell: wg pubkey < privatekey > publickey
  args:
    chdir: /etc/wireguard/
  when: public_key_stat_result.stat.exists == False

- name: Read the private key file contents
  shell: cat /etc/wireguard/privatekey
  register: privatekey_content

- name: Generate the wireguard config file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0600
  vars:
    private_key: "{{privatekey_content.stdout}}"

- name: Start/Restart wireguard service 
  systemd:
    name: wg-quick@wg0
    enabled: "{{enabled}}"
    state: restarted
